import { expect, test, describe } from 'vitest'
import { regexCharacterBetweenTypeAndScope } from '../regex'

describe('Character Between Type And Scope', () => {
  test("not", () => {
    expect("Update documentation".match(regexCharacterBetweenTypeAndScope)).toBeNull()
    expect("docs documentation".match(regexCharacterBetweenTypeAndScope)).toBeNull()
    expect("docs() documentation".match(regexCharacterBetweenTypeAndScope)).toBeNull()
    expect("docs(foo) documentation".match(regexCharacterBetweenTypeAndScope)).toBeNull()
    expect("docs () documentation".match(regexCharacterBetweenTypeAndScope)).toBeNull()
    expect("docs (foo) documentation".match(regexCharacterBetweenTypeAndScope)).toBeNull()

    expect("docs: Update documentation".match(regexCharacterBetweenTypeAndScope)).toBeNull()
    expect("docs!: Update documentation".match(regexCharacterBetweenTypeAndScope)).toBeNull()
    expect("docs! : Update documentation".match(regexCharacterBetweenTypeAndScope)).toBeNull()
    expect("docs !: Update documentation".match(regexCharacterBetweenTypeAndScope)).toBeNull()
    expect("docs ! : Update documentation".match(regexCharacterBetweenTypeAndScope)).toBeNull()
    expect("docs(foo): Update documentation".match(regexCharacterBetweenTypeAndScope)).toBeNull()
    expect("docs(foo)!: Update documentation".match(regexCharacterBetweenTypeAndScope)).toBeNull()
    expect("docs(): Update documentation".match(regexCharacterBetweenTypeAndScope)).toBeNull()
    expect("docs()!: Update documentation".match(regexCharacterBetweenTypeAndScope)).toBeNull()

    expect(" docs: Update documentation".match(regexCharacterBetweenTypeAndScope)).toBeNull()
    expect(" docs!: Update documentation".match(regexCharacterBetweenTypeAndScope)).toBeNull()
    expect(" docs! : Update documentation".match(regexCharacterBetweenTypeAndScope)).toBeNull()
    expect(" docs !: Update documentation".match(regexCharacterBetweenTypeAndScope)).toBeNull()
    expect(" docs ! : Update documentation".match(regexCharacterBetweenTypeAndScope)).toBeNull()
    expect(" docs (foo): Update documentation".match(regexCharacterBetweenTypeAndScope)).toBeNull()
    expect(" docs (foo)!: Update documentation".match(regexCharacterBetweenTypeAndScope)).toBeNull()
    expect(" docs (foo) !: Update documentation".match(regexCharacterBetweenTypeAndScope)).toBeNull()
    expect(" docs (foo)! : Update documentation".match(regexCharacterBetweenTypeAndScope)).toBeNull()
    expect(" docs (foo) ! : Update documentation".match(regexCharacterBetweenTypeAndScope)).toBeNull()
    expect(" docs (): Update documentation".match(regexCharacterBetweenTypeAndScope)).toBeNull()
    expect(" docs ()!: Update documentation".match(regexCharacterBetweenTypeAndScope)).toBeNull()
    expect(" docs () !: Update documentation".match(regexCharacterBetweenTypeAndScope)).toBeNull()
    expect(" docs ()! : Update documentation".match(regexCharacterBetweenTypeAndScope)).toBeNull()
    expect(" docs () ! : Update documentation".match(regexCharacterBetweenTypeAndScope)).toBeNull()

    expect("docs:".match(regexCharacterBetweenTypeAndScope)).toBeNull()
    expect("docs!:".match(regexCharacterBetweenTypeAndScope)).toBeNull()
    expect("docs !:".match(regexCharacterBetweenTypeAndScope)).toBeNull()
    expect("docs! :".match(regexCharacterBetweenTypeAndScope)).toBeNull()
    expect("docs ! :".match(regexCharacterBetweenTypeAndScope)).toBeNull()
    expect("docs(foo):".match(regexCharacterBetweenTypeAndScope)).toBeNull()
    expect("docs(foo)!:".match(regexCharacterBetweenTypeAndScope)).toBeNull()
    expect("docs():".match(regexCharacterBetweenTypeAndScope)).toBeNull()
    expect("docs()!:".match(regexCharacterBetweenTypeAndScope)).toBeNull()

    expect("docs: ".match(regexCharacterBetweenTypeAndScope)).toBeNull()
    expect("docs!: ".match(regexCharacterBetweenTypeAndScope)).toBeNull()
    expect("docs !: ".match(regexCharacterBetweenTypeAndScope)).toBeNull()
    expect("docs! : ".match(regexCharacterBetweenTypeAndScope)).toBeNull()
    expect("docs ! : ".match(regexCharacterBetweenTypeAndScope)).toBeNull()
  })
  
  test("match", () => {
    expect("docsfoo() : Update documentation".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo()! : Update documentation".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo() !: Update documentation`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo() ! : Update documentation`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo(foo) : Update documentation".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo(foo)! : Update documentation".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo) !: Update documentation`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo) ! : Update documentation`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo(foo foo) : Update documentation".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo(foo foo)! : Update documentation".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo foo) !: Update documentation`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo foo) ! : Update documentation`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo() :Update documentation".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo()! :Update documentation".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo() !:Update documentation`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo() ! :Update documentation`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo(foo) :Update documentation".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo(foo)! :Update documentation".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo) !:Update documentation`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo) ! :Update documentation`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo(foo foo) :Update documentation".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo(foo foo)! :Update documentation".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo foo) !:Update documentation`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo foo) ! :Update documentation`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo() :".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo()! :".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo() !:`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo() ! :`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo(foo) :".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo(foo)! :".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo) !:`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo) ! :`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo(foo foo) :".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo(foo foo)! :".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo foo) !:`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo foo) ! :`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')

    expect("docsfoo()foo: Update documentation".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo()!foo: Update documentation".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo()foo!: Update documentation`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo()foo!foo: Update documentation`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo(foo)foo: Update documentation".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo(foo)!foo: Update documentation".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo)foo!: Update documentation`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo)foo!foo: Update documentation`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo(foo foo)foo: Update documentation".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo(foo foo)!foo: Update documentation".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo foo)foo!: Update documentation`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo foo)foo!foo: Update documentation`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo()foo:Update documentation".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo()!foo:Update documentation".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo()foo!:Update documentation`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo()foo!foo:Update documentation`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo(foo)foo:Update documentation".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo(foo)!foo:Update documentation".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo)foo!:Update documentation`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo)foo!foo:Update documentation`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo(foo foo)foo:Update documentation".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo(foo foo)!foo:Update documentation".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo foo)foo!:Update documentation`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo foo)foo!foo:Update documentation`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo()foo:".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo()!foo:".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo()foo!:`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo()foo!foo:`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo(foo)foo:".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo(foo)!foo:".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo)foo!:`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo)foo!foo:`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo(foo foo)foo:".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo(foo foo)!foo:".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo foo)foo!:`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo foo)foo!foo:`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')

    expect("docsfoo() foo: Update documentation".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo()foo : Update documentation".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo() foo : Update documentation".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo() !foo: Update documentation".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo() ! foo: Update documentation".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo() ! foo : Update documentation".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo() foo!: Update documentation`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo() foo !: Update documentation`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo() foo ! : Update documentation`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo() foo!foo: Update documentation`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo() foo !foo: Update documentation`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo() foo ! foo: Update documentation`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo() foo ! foo : Update documentation`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo(foo) foo: Update documentation".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo(foo)foo : Update documentation".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo(foo) foo : Update documentation".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo(foo) !foo: Update documentation".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo(foo) ! foo: Update documentation".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo(foo) ! foo : Update documentation".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo) foo!: Update documentation`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo) foo !: Update documentation`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo) foo ! : Update documentation`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo) foo!foo: Update documentation`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo) foo !foo: Update documentation`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo) foo ! foo: Update documentation`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo) foo ! foo : Update documentation`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo(foo foo) foo: Update documentation".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo(foo foo)foo : Update documentation".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo(foo foo) foo : Update documentation".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo(foo foo) !foo: Update documentation".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo(foo foo) ! foo: Update documentation".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo(foo foo) ! foo : Update documentation".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo foo) foo!: Update documentation`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo foo) foo !: Update documentation`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo foo) foo ! : Update documentation`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo foo) foo!foo: Update documentation`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo foo) foo !foo: Update documentation`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo foo) foo ! foo: Update documentation`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo foo) foo ! foo : Update documentation`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')

    expect("docsfoo() foo:".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo()foo :".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo() foo :".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo() !foo:".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo() ! foo:".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo() ! foo :".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo() foo!:`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo() foo !:`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo() foo ! :`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo() foo!foo:`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo() foo !foo:`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo() foo ! foo:`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo() foo ! foo :`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo(foo) foo:".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo(foo)foo :".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo(foo) foo :".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo(foo) !foo:".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo(foo) ! foo:".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo(foo) ! foo :".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo) foo!:`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo) foo !:`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo) foo ! :`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo) foo!foo:`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo) foo !foo:`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo) foo ! foo:`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo) foo ! foo :`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo(foo foo) foo:".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo(foo foo)foo :".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo(foo foo) foo :".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo(foo foo) !foo:".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo(foo foo) ! foo:".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect("docsfoo(foo foo) ! foo :".match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo foo) foo!:`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo foo) foo !:`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo foo) foo ! :`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo foo) foo!foo:`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo foo) foo !foo:`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo foo) foo ! foo:`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
    expect(`docsfoo(foo foo) foo ! foo :`.match(regexCharacterBetweenTypeAndScope)?.groups?.position).toBe('foo')
  })
})
